baseURL = "https://recipes.jaynewstrom.com/"
languageCode = "en-us"
title = "Recipes"

theme = "dot"

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    icon = "foo"
  [[menu.main]]
    name = "Meal Types"
    url = "/meal-types/"
    icon = "bar"

[taxonomies]
  tag = "tags"
  meal-type = "meal-types"
