baseURL = "/"
languageCode = "en-us"
title = "Recipes"

theme = "dot"

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    name = "Meal Types"
    url = "/meal-types/"

[taxonomies]
  tag = "tags"
  meal-type = "meal-types"
