name: Hugo

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - terraform
    tags:
      - .*

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hugo
        uses: peaceiris/actions-hugo@v2
        with:
          version: 0.91.0
      - name: Build search index
        run: ./download-and-run-hugo-to-json.sh
      - name: Build
        run: hugo --minify
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
        if: github.event_name == 'push'
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'public'
        if: github.event_name == 'push'
      - uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
        if: github.event_name == 'push'
